version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-slim4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db_init.sql:/db_init.sql
      - mysql_data:/var/lib/mysql
    ports:
     - 127.0.0.1:3306:3306
    networks:
      - app-network
  php-fpm:
    build:
      context: ./
      dockerfile: Dockerfile.php
    volumes:
     - ./src/:/var/www
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx-slim4
    volumes:
     - ./src/:/var/www
     - ./docker/nginx/slim4.conf:/etc/nginx/conf.d/default.conf
    ports:
     - 127.0.0.1:88:80
    networks:
      - app-network
  phpmyadmin: 
    image: phpmyadmin:latest
    ports:
      - 127.0.0.1:8080:80
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mysql_data: